name: Test
on:
  pull_request:
  push:
    paths:
      - "**.go"
    branches:
      - main
      - release/**

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        part: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"]
    steps:
      - uses: actions/setup-python@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            "!test/"
            go.mod
            go.sum
            Makefile
      - name: Run Go Tests
        run: |
          NUM_SPLIT=20
          make test-group-${{matrix.part}} NUM_SPLIT=20
        if: env.GIT_DIFF

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ github.sha }}-${{ matrix.part }}-coverage"
          path: ./path/to/your/coverage/${{ matrix.part }}.out
        if: env.GIT_DIFF

  upload-coverage-report:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: "${{ github.sha }}-*"

      - name: Merge coverage reports
        run: |
          gocovmerge ./*-coverage > coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
